version: '3.5'

services:

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis

  beeg_db:
    container_name: beeg_db
    image: mysql
    restart: always
    env_file: ./.env
    volumes:
      - mysql_data:/var/lib/mysql 
    expose: 
      - 3306

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
       - DB_CON=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:3306)/${MYSQL_DATABASE}
       - DB_TEST_CON=mysql://beeg:password@db:3306/beeg_test
    command: reflex -c reflex.conf
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - beeg_db
    

volumes:
  mysql_data: {}
  redis_data: {}