version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    env_file: ./.env
    volumes:
      - mysql_data:/var/lib/mysql 
    ports: 
      - 3306:3306

volumes:
  mysql_data: {}
  redis_data: {}